services:
  dev:
    build:
      context: .
      target: dev
    user: "${DOCKER_UID:-1000}:${DOCKER_GID:-1000}"
    working_dir: /app
    environment:
      - GH_TOKEN
      - GITHUB_TOKEN
    volumes:
      - .:/app
      - cargo:/cargo
      - target:/cargo-target

  wine:
    build:
      context: .
      target: wine
    user: "${DOCKER_UID:-1000}:${DOCKER_GID:-1000}"
    working_dir: /app
    volumes:
      - .:/app
      - target:/cargo-target:ro
      - wineprefix:/wine

volumes:
  cargo:
  target:
  wineprefix:
